version: '3.8'

services: 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - ./environment.env
    volumes:
      - ./api/:/app/
    depends_on:
      - kafka

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - zookeeper
    env_file:
      - ./environment.env
    volumes:
      - ./worker/:/app/
    command: faust -A worker.app worker -l info
    ports:
      - 6066:6066

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    ports:
      - 2181:2181
    env_file:
      - ./environment.env

  kafka:
    image: confluentinc/cp-kafka:6.2.1
    hostname: kafka
    ports:
      - 9092:9092
    env_file:
      - ./environment.env