FROM node:18.16.0-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire app directory
COPY . .

# Set environment variable for development
ENV NODE_ENV=development

# Set environment variable to enable hot-reloading
ENV CHOKIDAR_USEPOLLING=true

# Expose the app port
EXPOSE 3000

# Start the development server
CMD ["npm", "start"]