#===================================================
FROM golang:1.20

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY ./app/ /app/

COPY ./app/go.mod ./app/go.sum ./


RUN go mod download

CMD ["air"]

