#===================================================
FROM golang:1.20

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY ./app/ /app/

COPY ./app/go.mod ./app/go.sum ./


RUN go mod download

# # Install air for live-reloading
# RUN go get -u github.com/cosmtrek/air

# Set the entrypoint to run the application with air
ENTRYPOINT ["air", "-c", ".air.toml"]

