version: '3.9'

services:
  app-golang-dev:
    build:
      dockerfile: ./Dockerfile.dev
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    env_file:
      - environment.env
    command: air