name: Deploy to Heroku on Client Changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  PROJECT_NAME: "doc-extractor"
  VERSION: "latest"
  HEROKU_CLIENT_APP: "doc-extractor-fe"

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get folder changes
        id: get-changes-folder
        run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^client/')
          echo "changes=${changes}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker image
        if: ${{ env.changes != '' }}
        run: |
          echo "Changes found in client folder, building Docker image..."
          docker buildx create --use
          docker buildx build --file client/Dockerfile --tag $DOCKER_USERNAME/$PROJECT_NAME:client-$VERSION client/

      - name: Push Docker image to Docker Hub
        if: ${{ env.changes != '' }}
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push $DOCKER_USERNAME/$PROJECT_NAME:client-$VERSION

      - name: Install Heroku CLI
        run: npm install -g heroku

      - name: Login to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Release Docker image to Heroku
        if: ${{ env.changes != '' }}
        run: |
          echo "Releasing Docker image to Heroku..."
          heroku container:release web --app $HEROKU_CLIENT_APP
