name: Deploy to Heroku on Client Changes

on:
  pull_request:
    branches: [ "main" ]
    
env:
    PROJECT_NAME: "doc-extractor"
    VERSION: "latest"
    DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    HEROKU_CLIENT_APP: "doc-extractor-fe"

jobs:
  deploy-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Heroku
        run: heroku container:login
  
      - name: Build and Push Docker image
        run: |
          cd client
          docker build -t registry.heroku.com/doc-extractor-fe/web -f Dockerfile.heroku .
          docker push registry.heroku.com/doc-extractor-fe/web

      - name: Release to Heroku
        run: heroku container:release web -a doc-extractor-fe
        

      - name: Release Docker image to Heroku
        run: |
          echo "Releasing Docker image to Heroku..."
          heroku container:release web --app $HEROKU_CLIENT_APP
