name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  VERSION: "latest"

jobs:

  build_and_push:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - name: API
            folder: api
            image: $DOCKERHUB_USERNAME/$PROJECT_NAME:api-$VERSION
            if: true
          - name: CLIENT
            folder: client
            image: $DOCKERHUB_USERNAME/$PROJECT_NAME:client-$VERSION
            if: ${{ github.event_path == 'client' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Build Image
        if: matrix.if
        run: |
          cd ${{ matrix.folder }}
          docker build -t ${{ matrix.image }}
      - name: Push Image
        if: matrix.if
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ${{ matrix.image }}
