import os
import json

# Project config
PIPELINE_NAME='XTRACT-PIPELINE'

# Kafka config
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS')
KAFKA_BOOTSTRAP_BROKER = 'kafka://' + KAFKA_BOOTSTRAP_SERVERS
KAFKA_TOPIC_PARTITIONS = 8

AGENT_CONFIG_PATH = os.getenv('AGENT_CONFIG_PATH')
AGENTS =  json.load(open(AGENT_CONFIG_PATH, 'rb'))